### ISSUE TITLE
`barrier.__slots__` incorrectly defined

### ISSUE THREAD

**Issue by adamchainz** [celery/vine#114]
0ce42bff76c205a7317d280ac0eb599ad8260a00 muted the Flake8 warning about `__slots__` being unused, which is occurring because it’s defined *within* the `__init__` method. The correct fix is to unindent `__slots__` so that it appears within the class definition, for example see https://wiki.python.org/moin/UsingSlots

**Comment by thedrow** [comment]
Care to contribute a fix?

**Comment by auvipy** [comment]
Prospective fix https://github.com/celery/vine/pull/115
