### ISSUE TITLE
Use WeakMethod for bound functions

### ISSUE THREAD

**Issue by georgepsarakis** [celery/vine#21]
Weak references to bound methods cannot work and thus the promise object cannot be created reliably, when the `weak` parameter is `True`.

In order to properly create weak references to functions that are bound to a class instance, we need to:
1. Create a backport of `weakref.WeakMethod` for Python versions before 3.4.
2. Detect if the function passed to `promise` is bound.
3. If (2) is true, use `WeakMethod` instead of `ref`.

Reference: https://github.com/celery/celery/pull/4839#issuecomment-399633253

**Comment by thedrow** [comment]
It turns out we do have a backport :)
https://github.com/celery/celery/blob/master/celery/utils/dispatch/weakref_backports.py

**Comment by thedrow** [comment]
Yes we should.

**Comment by georgepsarakis** [comment]
@auvipy @thedrow I am working on this, since it seems to affect a lot of Celery users. I will open a PR shortly.

**Comment by auvipy** [comment]
please :)
