### ISSUE TITLE
Please consider adding python_requires to vine 5 betas (and yanking 5.0.0a1 from pypi)

### ISSUE THREAD

**Issue by ThiefMaster** [celery/vine#34]
Currently someone who does a `pip install -U --pre` on a package that depends on celery (and thus indirectly on vine) on Python 2 ends up with vine 5.0.0a1, which is of course broken on Python 2.

It would be nice to use the appropriate [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) specifier in setup.py to avoid this - and then possibly remove 5.0.0a1 from PyPI and replace it with 5.0.0a2 that has these specifiers. (generally removing packages from PyPI is a bad idea, but for an alpha it's very unlikely that anyone depends on that particular version in their requirements)

**Comment by thedrow** [comment]
Done.
